spring.application.name=secure-api-hardening

# Database - Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/secure-api-hardening
spring.datasource.username=postgres
spring.datasource.password=1234

# hibernate-sql
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# OAuth2 Resource Server - validates JWTs issued by the local Keycloak container.
# Spring Boot derives the JWK Set URL (the public key endpoint) from this issuer automatically.
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/secure-api-hardening