spring.application.name=secure-api-hardening

# Database - Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/secure-api-hardening
spring.datasource.username=postgres
spring.datasource.password=1234

# hibernate-sql
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true